- name: Demo on conditions
  hosts: localhost
  connection: localhost
  tasks:
    - name: Print Helle Universe
      ansible.buitin.debug:
         msg: Hello Universe
      when: what == "universe" 

   
    - name: Print Hello World
      ansible.builtin.debug:
         msg: Hello World
      when: what == "world"