- name: Demo on loops
  hosts: localhost
  connection: localhost
  tasks:
    - name: Print Fruit name
      ansible.builtin,debug:
        msg: Fruit Name - {{ item }}

      loop:
        - apple
        - orange
        - grape
        - banana  
    - name: Print Fruit Nmae with Quantity
      ansible.buitin.debug:
        msg: Fruit Name - {{ item.name }}, Quantity - {{ iteam.quantity}}

      loop:
            
       - { name: apple, quantity: 100 }
       - { name: orange, quantity: 200}
       - { name: grape, quantity: 300}
       - { name: banana, quantity: 500}    